version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - npm run build:prod
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Starting sync to S3 - `date`"
      - aws s3 sync dist/ s3://${DEPLOY_BUCKET}
      - aws s3 cp dist/index.html s3://${DEPLOY_BUCKET}/index.html --cache-control "no-store, no-cache, must-revalidate" --content-type "text/html"
      - aws cloudfront create-invalidation --distribution-id ${CF_ID} --paths "/index.html" "/bundle.js" "/output.css"
      - echo "Sync completed on `date`"